use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'RightDirectionTests' do
    testing_pods
end

pod 'SwiftHEXColors', '~> 1.0'

pod 'Reveal-iOS-SDK', :configurations => ['Debug']

